---
name: HelpUI
version: 1.0.2
api: [3.0.0, 4.0.0]
main: dev0990\Main
description: A PocketMine-MP & Altay Plugin by dev0990
author: dev0990
commands:
   hui:
     description: Get a list of all commands
   hversion:
     description: Get the version of HelpUI
   habout:
     description: About HelpUI 
...
